//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPathTeam.PGPEncryption.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPathTeam.PGPEncryption.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt a file using the provided private key and passphrase, then verify the file was signed by the matching public key.
        /// </summary>
        public static string DecryptAndVerifyFile_Description {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt and Verify File.
        /// </summary>
        public static string DecryptAndVerifyFile_DisplayName {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input encrypted and signed file.
        /// </summary>
        public static string DecryptAndVerifyFile_FileIn_Description {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_FileIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileIn.
        /// </summary>
        public static string DecryptAndVerifyFile_FileIn_DisplayName {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_FileIn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output decrypted and verified file.
        /// </summary>
        public static string DecryptAndVerifyFile_FileOut_Description {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_FileOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileOut.
        /// </summary>
        public static string DecryptAndVerifyFile_FileOut_DisplayName {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_FileOut_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to read in the Private Key.
        /// </summary>
        public static string DecryptAndVerifyFile_FilePrivateKey_Description {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_FilePrivateKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePrivateKey.
        /// </summary>
        public static string DecryptAndVerifyFile_FilePrivateKey_DisplayName {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_FilePrivateKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to read in the Public Key.
        /// </summary>
        public static string DecryptAndVerifyFile_FilePublicKey_Description {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_FilePublicKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePublicKey.
        /// </summary>
        public static string DecryptAndVerifyFile_FilePublicKey_DisplayName {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_FilePublicKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite output files.  Default: False.
        /// </summary>
        public static string DecryptAndVerifyFile_Overwrite_Description {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_Overwrite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string DecryptAndVerifyFile_Overwrite_DisplayName {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_Overwrite_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is a word or phrase used to decrypt your private key on your machine.
        /// </summary>
        public static string DecryptAndVerifyFile_Passphrase_Description {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_Passphrase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string DecryptAndVerifyFile_Passphrase_DisplayName {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_Passphrase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureString Passphrase is a word or phrase used to decrypt your private key on your machine.
        /// </summary>
        public static string DecryptAndVerifyFile_SecurePassphrase_Description {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_SecurePassphrase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurePassphrase.
        /// </summary>
        public static string DecryptAndVerifyFile_SecurePassphrase_DisplayName {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_SecurePassphrase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status codes or errors that were encountered during the Process.
        /// </summary>
        public static string DecryptAndVerifyFile_Status_Description {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DecryptAndVerifyFile_Status_DisplayName {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of operation.  True if successful.
        /// </summary>
        public static string DecryptAndVerifyFile_Verified_Description {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_Verified_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string DecryptAndVerifyFile_Verified_DisplayName {
            get {
                return ResourceManager.GetString("DecryptAndVerifyFile_Verified_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt a file using the matching private key and passphrase.
        /// </summary>
        public static string DecryptFile_Description {
            get {
                return ResourceManager.GetString("DecryptFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt File.
        /// </summary>
        public static string DecryptFile_DisplayName {
            get {
                return ResourceManager.GetString("DecryptFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input encrypted file.
        /// </summary>
        public static string DecryptFile_FileIn_Description {
            get {
                return ResourceManager.GetString("DecryptFile_FileIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileIn.
        /// </summary>
        public static string DecryptFile_FileIn_DisplayName {
            get {
                return ResourceManager.GetString("DecryptFile_FileIn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output decrypted file.
        /// </summary>
        public static string DecryptFile_FileOut_Description {
            get {
                return ResourceManager.GetString("DecryptFile_FileOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileOut.
        /// </summary>
        public static string DecryptFile_FileOut_DisplayName {
            get {
                return ResourceManager.GetString("DecryptFile_FileOut_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to read in the Private Key.
        /// </summary>
        public static string DecryptFile_FilePrivateKey_Description {
            get {
                return ResourceManager.GetString("DecryptFile_FilePrivateKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePrivateKey.
        /// </summary>
        public static string DecryptFile_FilePrivateKey_DisplayName {
            get {
                return ResourceManager.GetString("DecryptFile_FilePrivateKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite output files.  Default: False.
        /// </summary>
        public static string DecryptFile_Overwrite_Description {
            get {
                return ResourceManager.GetString("DecryptFile_Overwrite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string DecryptFile_Overwrite_DisplayName {
            get {
                return ResourceManager.GetString("DecryptFile_Overwrite_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is a word or phrase used to decrypt your private key on your machine.
        /// </summary>
        public static string DecryptFile_Passphrase_Description {
            get {
                return ResourceManager.GetString("DecryptFile_Passphrase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string DecryptFile_Passphrase_DisplayName {
            get {
                return ResourceManager.GetString("DecryptFile_Passphrase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of operation.  True if successful.
        /// </summary>
        public static string DecryptFile_Result_Description {
            get {
                return ResourceManager.GetString("DecryptFile_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string DecryptFile_Result_DisplayName {
            get {
                return ResourceManager.GetString("DecryptFile_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureString Passphrase is a word or phrase used to decrypt your private key on your machine.
        /// </summary>
        public static string DecryptFile_SecurePassphrase_Description {
            get {
                return ResourceManager.GetString("DecryptFile_SecurePassphrase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurePassphrase.
        /// </summary>
        public static string DecryptFile_SecurePassphrase_DisplayName {
            get {
                return ResourceManager.GetString("DecryptFile_SecurePassphrase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status codes or errors that were encountered during the Process.
        /// </summary>
        public static string DecryptFile_Status_Description {
            get {
                return ResourceManager.GetString("DecryptFile_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DecryptFile_Status_DisplayName {
            get {
                return ResourceManager.GetString("DecryptFile_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt a file using the provided public key and then cryptographically sign the file.
        /// </summary>
        public static string EncryptAndSignFile_Description {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt and Sign File.
        /// </summary>
        public static string EncryptAndSignFile_DisplayName {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input raw text file.
        /// </summary>
        public static string EncryptAndSignFile_FileIn_Description {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_FileIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileIn.
        /// </summary>
        public static string EncryptAndSignFile_FileIn_DisplayName {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_FileIn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output encrypted and signed file.
        /// </summary>
        public static string EncryptAndSignFile_FileOut_Description {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_FileOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileOut.
        /// </summary>
        public static string EncryptAndSignFile_FileOut_DisplayName {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_FileOut_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to read in the Private Key.
        /// </summary>
        public static string EncryptAndSignFile_FilePrivateKey_Description {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_FilePrivateKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePrivateKey.
        /// </summary>
        public static string EncryptAndSignFile_FilePrivateKey_DisplayName {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_FilePrivateKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to read in the Public Key.
        /// </summary>
        public static string EncryptAndSignFile_FilePublicKey_Description {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_FilePublicKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePublicKey.
        /// </summary>
        public static string EncryptAndSignFile_FilePublicKey_DisplayName {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_FilePublicKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite output files.  Default: False.
        /// </summary>
        public static string EncryptAndSignFile_Overwrite_Description {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_Overwrite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string EncryptAndSignFile_Overwrite_DisplayName {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_Overwrite_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is a word or phrase used to decrypt your private key on your machine.
        /// </summary>
        public static string EncryptAndSignFile_Passphrase_Description {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_Passphrase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string EncryptAndSignFile_Passphrase_DisplayName {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_Passphrase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of operation.  True if successful.
        /// </summary>
        public static string EncryptAndSignFile_Result_Description {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string EncryptAndSignFile_Result_DisplayName {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureString Passphrase is a word or phrase used to decrypt your private key on your machine.
        /// </summary>
        public static string EncryptAndSignFile_SecurePassphrase_Description {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_SecurePassphrase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurePassphrase.
        /// </summary>
        public static string EncryptAndSignFile_SecurePassphrase_DisplayName {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_SecurePassphrase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status codes or errors that were encountered during the Process.
        /// </summary>
        public static string EncryptAndSignFile_Status_Description {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string EncryptAndSignFile_Status_DisplayName {
            get {
                return ResourceManager.GetString("EncryptAndSignFile_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt a file using the provided public key.
        /// </summary>
        public static string EncryptFile_Description {
            get {
                return ResourceManager.GetString("EncryptFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt File.
        /// </summary>
        public static string EncryptFile_DisplayName {
            get {
                return ResourceManager.GetString("EncryptFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input raw text file.
        /// </summary>
        public static string EncryptFile_FileIn_Description {
            get {
                return ResourceManager.GetString("EncryptFile_FileIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileIn.
        /// </summary>
        public static string EncryptFile_FileIn_DisplayName {
            get {
                return ResourceManager.GetString("EncryptFile_FileIn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output encrypted file.
        /// </summary>
        public static string EncryptFile_FileOut_Description {
            get {
                return ResourceManager.GetString("EncryptFile_FileOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileOut.
        /// </summary>
        public static string EncryptFile_FileOut_DisplayName {
            get {
                return ResourceManager.GetString("EncryptFile_FileOut_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to read in the Public Key.
        /// </summary>
        public static string EncryptFile_FilePublicKey_Description {
            get {
                return ResourceManager.GetString("EncryptFile_FilePublicKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePublicKey.
        /// </summary>
        public static string EncryptFile_FilePublicKey_DisplayName {
            get {
                return ResourceManager.GetString("EncryptFile_FilePublicKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite output files.  Default: False.
        /// </summary>
        public static string EncryptFile_Overwrite_Description {
            get {
                return ResourceManager.GetString("EncryptFile_Overwrite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string EncryptFile_Overwrite_DisplayName {
            get {
                return ResourceManager.GetString("EncryptFile_Overwrite_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of operation.  True if successful.
        /// </summary>
        public static string EncryptFile_Result_Description {
            get {
                return ResourceManager.GetString("EncryptFile_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string EncryptFile_Result_DisplayName {
            get {
                return ResourceManager.GetString("EncryptFile_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status codes or errors that were encountered during the Process.
        /// </summary>
        public static string EncryptFile_Status_Description {
            get {
                return ResourceManager.GetString("EncryptFile_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string EncryptFile_Status_DisplayName {
            get {
                return ResourceManager.GetString("EncryptFile_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new public and private key for the provided Identity and passphrase.
        /// </summary>
        public static string GenerateKeys_Description {
            get {
                return ResourceManager.GetString("GenerateKeys_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Keys.
        /// </summary>
        public static string GenerateKeys_DisplayName {
            get {
                return ResourceManager.GetString("GenerateKeys_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to store the Private Key. The private key is the key that allows you to decrypt the messages sent to you based on your public key.
        /// </summary>
        public static string GenerateKeys_FilePrivateKey_Description {
            get {
                return ResourceManager.GetString("GenerateKeys_FilePrivateKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePrivateKey.
        /// </summary>
        public static string GenerateKeys_FilePrivateKey_DisplayName {
            get {
                return ResourceManager.GetString("GenerateKeys_FilePrivateKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to store the Public Key. The public key is the key that other people use to encrypt a message that only you can open.
        /// </summary>
        public static string GenerateKeys_FilePublicKey_Description {
            get {
                return ResourceManager.GetString("GenerateKeys_FilePublicKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePublicKey.
        /// </summary>
        public static string GenerateKeys_FilePublicKey_DisplayName {
            get {
                return ResourceManager.GetString("GenerateKeys_FilePublicKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient email address.
        /// </summary>
        public static string GenerateKeys_Identity_Description {
            get {
                return ResourceManager.GetString("GenerateKeys_Identity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string GenerateKeys_Identity_DisplayName {
            get {
                return ResourceManager.GetString("GenerateKeys_Identity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key size.  Default: 2048.
        /// </summary>
        public static string GenerateKeys_KeySize_Description {
            get {
                return ResourceManager.GetString("GenerateKeys_KeySize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeySize.
        /// </summary>
        public static string GenerateKeys_KeySize_DisplayName {
            get {
                return ResourceManager.GetString("GenerateKeys_KeySize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite output files.  Default: False.
        /// </summary>
        public static string GenerateKeys_Overwrite_Description {
            get {
                return ResourceManager.GetString("GenerateKeys_Overwrite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string GenerateKeys_Overwrite_DisplayName {
            get {
                return ResourceManager.GetString("GenerateKeys_Overwrite_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is a word or phrase used to encrypt your private key on your machine.
        /// </summary>
        public static string GenerateKeys_Passphrase_Description {
            get {
                return ResourceManager.GetString("GenerateKeys_Passphrase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string GenerateKeys_Passphrase_DisplayName {
            get {
                return ResourceManager.GetString("GenerateKeys_Passphrase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of operation.  True if successful.
        /// </summary>
        public static string GenerateKeys_Result_Description {
            get {
                return ResourceManager.GetString("GenerateKeys_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string GenerateKeys_Result_DisplayName {
            get {
                return ResourceManager.GetString("GenerateKeys_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureString Passphrase is a word or phrase used to encrypt your private key on your machine.
        /// </summary>
        public static string GenerateKeys_SecurePassphrase_Description {
            get {
                return ResourceManager.GetString("GenerateKeys_SecurePassphrase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurePassphrase.
        /// </summary>
        public static string GenerateKeys_SecurePassphrase_DisplayName {
            get {
                return ResourceManager.GetString("GenerateKeys_SecurePassphrase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status codes or errors that were encountered during the Process.
        /// </summary>
        public static string GenerateKeys_Status_Description {
            get {
                return ResourceManager.GetString("GenerateKeys_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string GenerateKeys_Status_DisplayName {
            get {
                return ResourceManager.GetString("GenerateKeys_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear signs a file using the provided private key and passphrase so that it is human readable.
        /// </summary>
        public static string SignClearFile_Description {
            get {
                return ResourceManager.GetString("SignClearFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Clear File.
        /// </summary>
        public static string SignClearFile_DisplayName {
            get {
                return ResourceManager.GetString("SignClearFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clear signed output file.
        /// </summary>
        public static string SignClearFile_FileOut_Description {
            get {
                return ResourceManager.GetString("SignClearFile_FileOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileOut.
        /// </summary>
        public static string SignClearFile_FileOut_DisplayName {
            get {
                return ResourceManager.GetString("SignClearFile_FileOut_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographically signs a file.
        /// </summary>
        public static string SignFile_Description {
            get {
                return ResourceManager.GetString("SignFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign File.
        /// </summary>
        public static string SignFile_DisplayName {
            get {
                return ResourceManager.GetString("SignFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input file to sign.
        /// </summary>
        public static string SignFile_FileIn_Description {
            get {
                return ResourceManager.GetString("SignFile_FileIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileIn.
        /// </summary>
        public static string SignFile_FileIn_DisplayName {
            get {
                return ResourceManager.GetString("SignFile_FileIn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output signed file.
        /// </summary>
        public static string SignFile_FileOut_Description {
            get {
                return ResourceManager.GetString("SignFile_FileOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileOut.
        /// </summary>
        public static string SignFile_FileOut_DisplayName {
            get {
                return ResourceManager.GetString("SignFile_FileOut_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to read in the Private Key.
        /// </summary>
        public static string SignFile_FilePrivateKey_Description {
            get {
                return ResourceManager.GetString("SignFile_FilePrivateKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePrivateKey.
        /// </summary>
        public static string SignFile_FilePrivateKey_DisplayName {
            get {
                return ResourceManager.GetString("SignFile_FilePrivateKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite output files.  Default: False.
        /// </summary>
        public static string SignFile_Overwrite_Description {
            get {
                return ResourceManager.GetString("SignFile_Overwrite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string SignFile_Overwrite_DisplayName {
            get {
                return ResourceManager.GetString("SignFile_Overwrite_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is a word or phrase used to decrypt your private key on your machine.
        /// </summary>
        public static string SignFile_Passphrase_Description {
            get {
                return ResourceManager.GetString("SignFile_Passphrase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string SignFile_Passphrase_DisplayName {
            get {
                return ResourceManager.GetString("SignFile_Passphrase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of operation.  True if successful.
        /// </summary>
        public static string SignFile_Result_Description {
            get {
                return ResourceManager.GetString("SignFile_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string SignFile_Result_DisplayName {
            get {
                return ResourceManager.GetString("SignFile_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureString Passphrase is a word or phrase used to decrypt your private key on your machine.
        /// </summary>
        public static string SignFile_SecurePassphrase_Description {
            get {
                return ResourceManager.GetString("SignFile_SecurePassphrase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurePassphrase.
        /// </summary>
        public static string SignFile_SecurePassphrase_DisplayName {
            get {
                return ResourceManager.GetString("SignFile_SecurePassphrase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status codes or errors that were encountered during the Process.
        /// </summary>
        public static string SignFile_Status_Description {
            get {
                return ResourceManager.GetString("SignFile_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SignFile_Status_DisplayName {
            get {
                return ResourceManager.GetString("SignFile_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the validity period of a PGP Public Key File.
        /// </summary>
        public static string VerifyKeyValidity_Description {
            get {
                return ResourceManager.GetString("VerifyKeyValidity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Key Validity.
        /// </summary>
        public static string VerifyKeyValidity_DisplayName {
            get {
                return ResourceManager.GetString("VerifyKeyValidity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to read in the Public Key.
        /// </summary>
        public static string VerifyKeyValidity_FilePublicKey_Description {
            get {
                return ResourceManager.GetString("VerifyKeyValidity_FilePublicKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePublicKey.
        /// </summary>
        public static string VerifyKeyValidity_FilePublicKey_DisplayName {
            get {
                return ResourceManager.GetString("VerifyKeyValidity_FilePublicKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key expiration date or errors that were encountered during the Process.
        /// </summary>
        public static string VerifyKeyValidity_Status_Description {
            get {
                return ResourceManager.GetString("VerifyKeyValidity_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string VerifyKeyValidity_Status_DisplayName {
            get {
                return ResourceManager.GetString("VerifyKeyValidity_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if Public Key is valid.
        /// </summary>
        public static string VerifyKeyValidity_Verified_Description {
            get {
                return ResourceManager.GetString("VerifyKeyValidity_Verified_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string VerifyKeyValidity_Verified_DisplayName {
            get {
                return ResourceManager.GetString("VerifyKeyValidity_Verified_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify a clear signed file was signed by the matching public key.
        /// </summary>
        public static string VerifySignedClearFile_Description {
            get {
                return ResourceManager.GetString("VerifySignedClearFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Signed Clear File.
        /// </summary>
        public static string VerifySignedClearFile_DisplayName {
            get {
                return ResourceManager.GetString("VerifySignedClearFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input clear signed file.
        /// </summary>
        public static string VerifySignedClearFile_FileIn_Description {
            get {
                return ResourceManager.GetString("VerifySignedClearFile_FileIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileIn.
        /// </summary>
        public static string VerifySignedClearFile_FileIn_DisplayName {
            get {
                return ResourceManager.GetString("VerifySignedClearFile_FileIn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify a file was signed by the matching public key.
        /// </summary>
        public static string VerifySignedFile_Description {
            get {
                return ResourceManager.GetString("VerifySignedFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Signed File.
        /// </summary>
        public static string VerifySignedFile_DisplayName {
            get {
                return ResourceManager.GetString("VerifySignedFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input signed file.
        /// </summary>
        public static string VerifySignedFile_FileIn_Description {
            get {
                return ResourceManager.GetString("VerifySignedFile_FileIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileIn.
        /// </summary>
        public static string VerifySignedFile_FileIn_DisplayName {
            get {
                return ResourceManager.GetString("VerifySignedFile_FileIn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path to read in the Public Key.
        /// </summary>
        public static string VerifySignedFile_FilePublicKey_Description {
            get {
                return ResourceManager.GetString("VerifySignedFile_FilePublicKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePublicKey.
        /// </summary>
        public static string VerifySignedFile_FilePublicKey_DisplayName {
            get {
                return ResourceManager.GetString("VerifySignedFile_FilePublicKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status codes or errors that were encountered during the Process.
        /// </summary>
        public static string VerifySignedFile_Status_Description {
            get {
                return ResourceManager.GetString("VerifySignedFile_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string VerifySignedFile_Status_DisplayName {
            get {
                return ResourceManager.GetString("VerifySignedFile_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if Signature matches with Public Key.
        /// </summary>
        public static string VerifySignedFile_Verified_Description {
            get {
                return ResourceManager.GetString("VerifySignedFile_Verified_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string VerifySignedFile_Verified_DisplayName {
            get {
                return ResourceManager.GetString("VerifySignedFile_Verified_DisplayName", resourceCulture);
            }
        }
    }
}
